<a href="https://colab.research.google.com/github/saloni-deshmukh/Bharat-Intern-House-Price-Prediction-ML/blob/main/Pandas-Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data = {'Name':['John','Anna','Peter','Linda'],
        'Age':[28,34,29,40],
        'City':['New York','Paris','Berlin','London']}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df


Name  Age      City
0   John   28  New York
1   Anna   34     Paris
2  Peter   29    Berlin
3  Linda   40    London

In [ ]:
#1 Write a command to select all rows where the value in the 'Age' column is greater than 30 using `loc`

df.loc[df['Age']>30]


Name  Age    City
1   Anna   34   Paris
3  Linda   40  London

In [ ]:
#2 How would you select the 'Name' and 'City' columns for rows where the 'Age' column is less than or equal to 29 in the given DataFrame `df`

df.loc[(df['Age']<=29),['Name','City']]


Name      City
0   John  New York
2  Peter    Berlin

In [ ]:
#3 Write a command to select the first two rows using `iloc`

df.iloc[0:2,:]

Name  Age      City
0  John   28  New York
1  Anna   34     Paris

In [ ]:
#4 How would you select the 'Name' and 'City' columns for the last two rows

df.iloc[-2:,[0,2]]


Name    City
2  Peter  Berlin
3  Linda  London

In [ ]:
#5 Explain the difference between `loc` and `iloc` in pandas. Provide an example using the DataFrame `df`

# loc - LABEL-based indexing
#iloc - iINTEGER - based indexing

#example : to access the data of 2nd, 3rd row & 2nd, 3rd column

#using LOC

l1 = df.loc[2:3,'Age':'City']
print(l1)

#using ILOC

l2 = df.iloc[2:4, 1:3]
print(l2)


   Age    City
2   29  Berlin
3   40  London
   Age    City
2   29  Berlin
3   40  London


In [ ]:
#6 Write a command to set the 'City' column to 'Unknown' for all rows where the 'Age' is greater than 30 using `loc

df.loc[df['Age']>30, 'City'] = 'Unknown'
print(df)


    Name  Age      City
0   John   28  New York
1   Anna   34   Unknown
2  Peter   29    Berlin
3  Linda   40   Unknown


In [ ]:
#7 Using `iloc`, how would you select the second and third rows and the 'Name' and 'City' columns of the DataFrame `df`

df.iloc[1:3, [0,2]]


Name    City
1   Anna   Paris
2  Peter  Berlin

In [ ]:
#8 Write a command to select all columns for rows where 'City' is 'Paris' using `loc`

df.loc[df['City']=='Paris']


Name  Age   City
1  Anna   34  Paris

In [ ]:
#9 Using `iloc`, how would you select every other row and all columns from the DataFrame `df` starting from the first row?

df.iloc[0:4:2]


Name  Age      City
0   John   28  New York
2  Peter   29    Berlin

In [ ]:
#10 Using `loc`, write a command to select all rows where 'Name' starts with the letter 'P' in the DataFrame `df`

df.loc[df['Name'].str.startswith('P')]


Name  Age    City
2  Peter   29  Berlin

In [ ]:

import numpy as np


In [ ]:
#11 Write a command to create a 1D numpy array with values ranging from 0 to 9.

a = np.array(range(0,10))

print(a)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#12 Using numpy, generate a 2D array of shape (3, 3) with random integer values between 10 and 50.

a = np.random.randint(10,50,(3,3))

a

array([[27, 23, 45],
       [31, 28, 27],
       [15, 22, 47]])

In [ ]:
#13 Write a command to create a numpy array with 5 evenly spaced values between 0 and 1.

np.linspace(0,1,5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
#14 Using numpy, create an array with values starting from 10 to 100 with a step size of 10

np.array(range(10,100,10))


array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#15 Convert the 1D numpy array `[1, 2, 3, 4, 5, 6]` into a 2x3 2D array and slice the array to get the firs row

a = np.array([1,2,3,4,5,6])
b = a.reshape((2,3))
sliced = b[0]

b

sliced


array([1, 2, 3])